// Code generated by sqlc. DO NOT EDIT.

package pgstore

import (
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID       uuid.UUID
	TripID   uuid.UUID
	Title    string
	OccursAt time.Time
}

type Link struct {
	ID     uuid.UUID
	TripID uuid.UUID
	Title  string
	Url    string
}

type Participant struct {
	ID          uuid.UUID
	TripID      uuid.UUID
	Email       string
	IsConfirmed bool
}

type Trip struct {
	ID          uuid.UUID
	Destination string
	OwnerEmail  string
	OwnerName   string
	IsConfirmed bool
	StartsAt    time.Time
	EndsAt      time.Time
}
